# Generated by Django 5.0.6 on 2026-06-23 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0002_cierremensualfinanciero'),
        ('iglesias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AporteNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_aporte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('cierre', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aporte_nacional', to='finanzas.cierremensualfinanciero')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes_nacionales_generados', to=settings.AUTH_USER_MODEL)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
            ],
            options={
                'verbose_name': 'aporte nacional',
                'verbose_name_plural': 'aportes nacionales',
                'ordering': ('-anio', '-mes', 'iglesia__nombre'),
                'unique_together': {('iglesia', 'anio', 'mes')},
            },
        ),
    ]
