# Generated by Django 5.0.6 on 2026-06-27 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_alter_miembro_iglesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('DISCIPLINA', 'En disciplina'), ('TRASLADADO', 'Trasladado'), ('FALLECIDO', 'Fallecido')], default='ACTIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialPastoralMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('BAUTISMO', 'Bautismo'), ('ADMISION', 'Admision formal'), ('BAJA_VOLUNTARIA', 'Baja voluntaria'), ('RESTAURACION', 'Restauracion'), ('DISCIPLINA', 'Disciplina'), ('SUSPENSION', 'Suspension'), ('FALLECIMIENTO', 'Fallecimiento')], max_length=30)),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('activo_anterior', models.BooleanField(default=True)),
                ('activo_nuevo', models.BooleanField(default=True)),
                ('resumen_cierre', models.JSONField(blank=True, null=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_pastoral', to='miembros.miembro')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_pastoral_registrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial pastoral de miembro',
                'verbose_name_plural': 'historial pastoral de miembros',
                'ordering': ('-fecha', '-creado_en'),
            },
        ),
    ]
