# Generated by Django 5.0.6 on 2026-06-23 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesias', '0001_initial'),
        ('miembros', '0002_alter_miembro_iglesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('observacion_respuesta', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
                ('iglesia_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_recibidos', to='iglesias.iglesia')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='miembros.miembro')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_respondidos', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'traslado',
                'verbose_name_plural': 'traslados',
                'ordering': ('-fecha_solicitud', '-creado_en'),
            },
        ),
    ]
