# Generated by Django 5.0.6 on 2026-06-22 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesias', '0001_initial'),
        ('miembros', '0002_alter_miembro_iglesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='SOLICITADO', max_length=20)),
                ('motivo', models.TextField()),
                ('observacion_respuesta', models.TextField(blank=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('iglesia_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='iglesias.iglesia')),
                ('iglesia_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='iglesias.iglesia')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='miembros.miembro')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_respondidos', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'traslado de miembro',
                'verbose_name_plural': 'traslados de miembros',
                'ordering': ('-creado_en',),
            },
        ),
    ]
