# Generated by Django 5.0.6 on 2026-06-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traslados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trasladomiembro",
            name="observacion_recepcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trasladomiembro",
            name="recepcion_confirmada_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trasladomiembro",
            name="recepcion_confirmada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="traslados_recepciones_confirmadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
