# Generated by Django 5.0.6 on 2026-06-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traslados", "0002_recepcion_pastoral"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trasladomiembro",
            name="escuela_dominical_destino_revisada_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trasladomiembro",
            name="familia_destino_revisada_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trasladomiembro",
            name="observacion_escuela_dominical_destino",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trasladomiembro",
            name="observacion_familia_destino",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trasladomiembro",
            name="escuela_dominical_destino_revisada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="traslados_escuela_destino_revisados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trasladomiembro",
            name="familia_destino_revisada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="traslados_familia_destino_revisados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
