# Generated by Django 5.0.6 on 2026-06-27 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familias', '0003_matrimonio'),
        ('miembros', '0002_alter_miembro_iglesia'),
        ('traslados', '0003_integracion_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladomiembro',
            name='es_familiar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trasladomiembro',
            name='familia_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_familiares', to='familias.familia'),
        ),
        migrations.CreateModel(
            name='TareaPastoralTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=180)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('completada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_traslado_completadas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_traslado_creadas', to=settings.AUTH_USER_MODEL)),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_pastorales', to='traslados.trasladomiembro')),
            ],
            options={
                'verbose_name': 'tarea pastoral de traslado',
                'verbose_name_plural': 'tareas pastorales de traslado',
                'ordering': ('estado', 'creado_en'),
            },
        ),
        migrations.CreateModel(
            name='TrasladoFamiliarIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('relacion', models.CharField(blank=True, max_length=20)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_familiares_adicionales', to='miembros.miembro')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes_familiares', to='traslados.trasladomiembro')),
            ],
            options={
                'verbose_name': 'integrante de traslado familiar',
                'verbose_name_plural': 'integrantes de traslado familiar',
                'ordering': ('miembro__apellidos', 'miembro__nombres'),
                'unique_together': {('traslado', 'miembro')},
            },
        ),
    ]
