# Generated by Django 5.0.6 on 2026-06-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
    ]
