# Generated by Django 5.0.6 on 2026-06-23 00:50

from django.db import migrations, models


def migrar_roles_obsoletos(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    Group = apps.get_model("auth", "Group")
    mapeos = {
        "PRESIDENTE_NACIONAL": "ADMIN_NACIONAL",
        "VICEPRESIDENTE_NACIONAL": "ADMIN_NACIONAL",
        "SECRETARIO_NACIONAL": "ADMIN_NACIONAL",
        "TESORERO_NACIONAL": "ADMIN_NACIONAL",
        "AUDITOR_NACIONAL": "ADMIN_NACIONAL",
        "LIDER_MINISTERIO": "SOLO_LECTURA",
        "MAESTRO": "SOLO_LECTURA",
    }
    grupos = {grupo.name: grupo for grupo in Group.objects.filter(name__in=set(mapeos.values()))}

    for rol_anterior, rol_nuevo in mapeos.items():
        usuarios = list(Usuario.objects.filter(rol=rol_anterior))
        Usuario.objects.filter(pk__in=[usuario.pk for usuario in usuarios]).update(rol=rol_nuevo)
        grupo = grupos.get(rol_nuevo)
        if grupo is not None:
            for usuario in usuarios:
                usuario.groups.set([grupo])


def revertir_roles_obsoletos(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.RunPython(migrar_roles_obsoletos, revertir_roles_obsoletos),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN_NACIONAL', 'Admin nacional'), ('PASTOR_FILIAL', 'Pastor filial'), ('ENCARGADO_FILIAL', 'Encargado filial'), ('SECRETARIO_FILIAL', 'Secretario filial'), ('TESORERO_FILIAL', 'Tesorero filial'), ('SOLO_LECTURA', 'Solo lectura')], default='SOLO_LECTURA', max_length=40),
        ),
    ]
