# Generated by Django 5.0.6 on 2026-06-27 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_alter_asignacioncargo_iglesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncargo',
            name='asignacion_reemplazada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos', to='cargos.asignacioncargo'),
        ),
        migrations.AddField(
            model_name='asignacioncargo',
            name='tipo_asignacion',
            field=models.CharField(choices=[('TITULAR', 'Titular'), ('INTERINO', 'Interino'), ('SUPLENTE', 'Suplente')], default='TITULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='cargo',
            name='es_sensible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='requiere_documento_posesion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asignacioncargo',
            name='estado',
            field=models.CharField(choices=[('NOMBRADO', 'Nombrado'), ('VIGENTE', 'Vigente'), ('FINALIZADO', 'Finalizado'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialAsignacionCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('NOMBRAMIENTO', 'Nombramiento'), ('POSESION', 'Posesion'), ('RENUNCIA', 'Renuncia'), ('REEMPLAZO', 'Reemplazo')], max_length=30)),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_formal', to='cargos.asignacioncargo')),
                ('asignacion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_relacionado', to='cargos.asignacioncargo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_cargos_registrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial formal de cargo',
                'verbose_name_plural': 'historial formal de cargos',
                'ordering': ('-fecha', '-creado_en'),
            },
        ),
    ]
