# Generated by Django 5.0.6 on 2026-06-23 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
            ],
            options={
                'verbose_name': 'concepto financiero',
                'verbose_name_plural': 'conceptos financieros',
                'ordering': ('tipo', 'nombre'),
                'unique_together': {('iglesia', 'tipo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=255)),
                ('numero_comprobante', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=20)),
                ('fecha_anulacion', models.DateField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros_anulados', to=settings.AUTH_USER_MODEL)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.conceptofinanciero')),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento financiero',
                'verbose_name_plural': 'movimientos financieros',
                'ordering': ('-fecha', '-creado_en'),
            },
        ),
    ]
