# Generated by Django 5.0.6 on 2026-06-23 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('iglesias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreMensualFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='CERRADO', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('cerrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_financieros', to=settings.AUTH_USER_MODEL)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
            ],
            options={
                'verbose_name': 'cierre mensual financiero',
                'verbose_name_plural': 'cierres mensuales financieros',
                'ordering': ('-anio', '-mes', 'iglesia__nombre'),
                'unique_together': {('iglesia', 'anio', 'mes')},
            },
        ),
    ]
