# Generated by Django 5.0.6 on 2026-06-25 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_cierremensualfinanciero'),
        ('iglesias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cierremensualfinanciero',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cierremensualfinanciero',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CERRADO')), fields=('iglesia', 'anio', 'mes'), name='finanzas_cierre_cerrado_unico_por_mes'),
        ),
    ]
