# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("familias", "0002_alter_familia_iglesia"),
        ("iglesias", "0001_initial"),
        ("miembros", "0002_alter_miembro_iglesia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matrimonio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_matrimonio", models.DateField()),
                ("observacion", models.TextField(blank=True)),
                (
                    "conyuge_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matrimonios_como_conyuge_1",
                        to="miembros.miembro",
                    ),
                ),
                (
                    "conyuge_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matrimonios_como_conyuge_2",
                        to="miembros.miembro",
                    ),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matrimonios",
                        to="familias.familia",
                    ),
                ),
                (
                    "iglesia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_items",
                        to="iglesias.iglesia",
                    ),
                ),
            ],
            options={
                "verbose_name": "matrimonio",
                "verbose_name_plural": "matrimonios",
                "ordering": ("-fecha_matrimonio", "conyuge_1__apellidos", "conyuge_2__apellidos"),
            },
        ),
    ]
