# Generated by Django 5.0.6 on 2026-06-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesias', '0001_initial'),
        ('ministerios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministerio',
            name='iglesia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia'),
        ),
    ]
