# Generated by Django 5.0.6 on 2026-06-22 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerios', '0002_alter_ministerio_iglesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerio',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ministerios_liderados', to=settings.AUTH_USER_MODEL),
        ),
    ]
