# Generated by Django 5.0.6 on 2026-06-22 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela_dominical', '0003_procesopromocionescueladominical_and_more'),
        ('iglesias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoEscuelaDominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_graduacion', models.DateField()),
                ('nombre_alumno', models.CharField(max_length=250)),
                ('nivel_cursado', models.CharField(max_length=120)),
                ('periodo_lectivo', models.CharField(max_length=80)),
                ('nombre_pastor', models.CharField(max_length=180)),
                ('nombre_director', models.CharField(max_length=180)),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('ANULADO', 'Anulado')], default='EMITIDO', max_length=20)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados_escuela_anulados', to=settings.AUTH_USER_MODEL)),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_escuela_emitidos', to=settings.AUTH_USER_MODEL)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
                ('resultado_promocion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado', to='escuela_dominical.resultadopromocionescueladominical')),
            ],
            options={
                'verbose_name': 'certificado de Escuela Dominical',
                'verbose_name_plural': 'certificados de Escuela Dominical',
                'ordering': ('-fecha_emision', '-numero'),
            },
        ),
    ]
