# Generated by Django 5.0.6 on 2026-06-24 01:23

import apps.documentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('iglesias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('archivo', models.FileField(upload_to=apps.documentos.models.documento_upload_to, validators=[apps.documentos.models.validar_archivo_adjunto])),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('FOTO', 'Foto'), ('GARANTIA', 'Garantia'), ('ACTA', 'Acta'), ('COMPROBANTE', 'Comprobante'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_adjuntos_anulados', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento adjunto',
                'verbose_name_plural': 'documentos adjuntos',
                'ordering': ('-creado_en',),
            },
        ),
    ]
