# Generated by Django 5.0.6 on 2026-06-24 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=160)),
                ('categoria', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion_actual', models.CharField(max_length=160)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_REPARACION', 'En reparacion'), ('DADO_DE_BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=20)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('valor_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
                ('responsable_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_inventario_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activo de inventario',
                'verbose_name_plural': 'activos de inventario',
                'ordering': ('iglesia__nombre', 'codigo'),
                'unique_together': {('iglesia', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('UBICACION', 'Cambio de ubicacion'), ('RESPONSABLE', 'Cambio de responsable'), ('REPARACION', 'Reparacion o mantenimiento'), ('BAJA', 'Baja')], max_length=20)),
                ('fecha', models.DateField()),
                ('ubicacion_anterior', models.CharField(blank=True, max_length=160)),
                ('ubicacion_nueva', models.CharField(blank=True, max_length=160)),
                ('detalle', models.TextField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.activoinventario')),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_registrados', to=settings.AUTH_USER_MODEL)),
                ('responsable_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_responsable_anterior', to=settings.AUTH_USER_MODEL)),
                ('responsable_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_responsable_nuevo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ('-fecha', '-creado_en'),
            },
        ),
    ]
