# Generated by Django 5.0.6 on 2026-06-22 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iglesias', '0001_initial'),
        ('miembros', '0002_alter_miembro_iglesia'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEscuelaDominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=150)),
                ('aula', models.CharField(blank=True, max_length=100)),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('cupo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases_escuela_dominical', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_escuela_dominical', to='parametros.periodo')),
            ],
            options={
                'verbose_name': 'clase de Escuela Dominical',
                'verbose_name_plural': 'clases de Escuela Dominical',
                'ordering': ('nivel__orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='MatriculaEscuelaDominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RETIRADA', 'Retirada'), ('PROMOVIDA', 'Promovida')], default='ACTIVA', max_length=20)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_escuela_dominical', to='miembros.miembro')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='escuela_dominical.claseescueladominical')),
            ],
            options={
                'verbose_name': 'matricula de Escuela Dominical',
                'verbose_name_plural': 'matriculas de Escuela Dominical',
                'ordering': ('alumno__apellidos', 'alumno__nombres'),
            },
        ),
        migrations.CreateModel(
            name='NivelEscuelaDominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('edad_minima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edad_maxima', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
            ],
            options={
                'verbose_name': 'nivel de Escuela Dominical',
                'verbose_name_plural': 'niveles de Escuela Dominical',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.AddField(
            model_name='claseescueladominical',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='escuela_dominical.nivelescueladominical'),
        ),
        migrations.AddConstraint(
            model_name='matriculaescueladominical',
            constraint=models.UniqueConstraint(fields=('clase', 'alumno'), name='escuela_matricula_unica_por_clase'),
        ),
        migrations.AddConstraint(
            model_name='nivelescueladominical',
            constraint=models.UniqueConstraint(fields=('iglesia', 'nombre'), name='escuela_nivel_nombre_unico_por_iglesia'),
        ),
        migrations.AddConstraint(
            model_name='claseescueladominical',
            constraint=models.UniqueConstraint(fields=('iglesia', 'periodo', 'nombre'), name='escuela_clase_nombre_unico_por_periodo'),
        ),
    ]
