# Generated by Django 5.0.6 on 2026-06-22 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_dominical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEscuelaDominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('tema', models.CharField(blank=True, max_length=180)),
                ('observacion', models.TextField(blank=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='escuela_dominical.claseescueladominical')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_escuela_dominical_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesion de Escuela Dominical',
                'verbose_name_plural': 'sesiones de Escuela Dominical',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEscuelaDominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='escuela_dominical.matriculaescueladominical')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='escuela_dominical.sesionescueladominical')),
            ],
            options={
                'verbose_name': 'asistencia de Escuela Dominical',
                'verbose_name_plural': 'asistencias de Escuela Dominical',
                'ordering': ('matricula__alumno__apellidos', 'matricula__alumno__nombres'),
            },
        ),
        migrations.AddConstraint(
            model_name='sesionescueladominical',
            constraint=models.UniqueConstraint(fields=('clase', 'fecha'), name='escuela_sesion_unica_por_clase_fecha'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaescueladominical',
            constraint=models.UniqueConstraint(fields=('sesion', 'matricula'), name='escuela_asistencia_unica_por_sesion_matricula'),
        ),
    ]
