# Generated by Django 5.0.6 on 2026-06-22 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela_dominical', '0002_sesionescueladominical_asistenciaescueladominical_and_more'),
        ('iglesias', '0001_initial'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoPromocionEscuelaDominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_corte', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado')], default='BORRADOR', max_length=20)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promociones_escuela_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('iglesia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='iglesias.iglesia')),
                ('periodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones_escuela_destino', to='parametros.periodo')),
                ('periodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones_escuela_origen', to='parametros.periodo')),
            ],
            options={
                'verbose_name': 'proceso de promocion de Escuela Dominical',
                'verbose_name_plural': 'procesos de promocion de Escuela Dominical',
                'ordering': ('-fecha_corte', 'iglesia__nombre'),
            },
        ),
        migrations.CreateModel(
            name='ResultadoPromocionEscuelaDominical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('edad_al_corte', models.PositiveSmallIntegerField()),
                ('destino', models.CharField(choices=[('NIVEL_SIGUIENTE', 'Nivel siguiente'), ('JOVENES', 'Jovenes')], max_length=20)),
                ('sesiones_consideradas', models.PositiveSmallIntegerField(default=0)),
                ('presentes', models.PositiveSmallIntegerField(default=0)),
                ('ausentes', models.PositiveSmallIntegerField(default=0)),
                ('justificados', models.PositiveSmallIntegerField(default=0)),
                ('clase_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_promocion_destino', to='escuela_dominical.claseescueladominical')),
                ('matricula_destino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultado_promocion_origen', to='escuela_dominical.matriculaescueladominical')),
                ('matricula_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_promocion', to='escuela_dominical.matriculaescueladominical')),
                ('nivel_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_promocion_destino', to='escuela_dominical.nivelescueladominical')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='escuela_dominical.procesopromocionescueladominical')),
            ],
            options={
                'verbose_name': 'resultado de promocion de Escuela Dominical',
                'verbose_name_plural': 'resultados de promocion de Escuela Dominical',
                'ordering': ('matricula_origen__alumno__apellidos', 'matricula_origen__alumno__nombres'),
            },
        ),
        migrations.AddConstraint(
            model_name='procesopromocionescueladominical',
            constraint=models.UniqueConstraint(fields=('iglesia', 'periodo_origen', 'periodo_destino'), name='escuela_promocion_unica_por_periodos'),
        ),
        migrations.AddConstraint(
            model_name='resultadopromocionescueladominical',
            constraint=models.UniqueConstraint(fields=('proceso', 'matricula_origen'), name='escuela_resultado_unico_por_proceso_matricula'),
        ),
    ]
